Config update

diff --git a/private_dot_local/bin/executable_update_system b/private_dot_local/bin/executable_update_system
--- a/private_dot_local/bin/executable_update_system
+++ b/private_dot_local/bin/executable_update_system
@@ -1,3 +1,6 @@
 #!/bin/sh
 
-sudo pacman -Syu --noconfirm
+sudo pacman -Syu --noconfirm || echo "Update failed"
+
+echo "Press enter to continue..."
+read
diff --git a/private_dot_local/bin/executable_update_system_and_shutdown b/private_dot_local/bin/executable_update_system_and_shutdown
--- a/private_dot_local/bin/executable_update_system_and_shutdown
+++ b/private_dot_local/bin/executable_update_system_and_shutdown
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-/home/friso/.local/bin/update_system
+sudo pacman -Syu --noconfirm || echo "Update failed. Press enter to quit." && read && exit
+
 echo "Done updating, shutting down in 3 seconds"
 sleep 3
 systemctl poweroff
